### ISSUE TITLE
juju generate-config isn't implemented

### ISSUE THREAD

**Issue by evilnick** [juju/juju-academy#11]
which we all know is to be used in preference to juju init

**Comment by marcoceppi** [comment]
Here's my proposed solution, feedback? :smiley_cat: 

![image](https://cloud.githubusercontent.com/assets/70613/2906460/1dcf5334-d611-11e3-9dfe-79a98ff3a99f.png)

---

I'll make sure both commands (init and generate-config) operate and are referenced in the tutorial

**Comment by kwmonroe** [comment]
s/generate/generate-config for commands and lesson checkpoint in:

https://github.com/juju/juju-academy/pull/22
